title: <p align="center">Manjiri Gajmal
logo: /assets/img/logo.png
description: <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  
show_downloads: true
google_analytics: I am currently working on data science related problem

theme: jekyll-theme-minimal
